
special.o:	/usr/include/errno.h
special.o:	/usr/include/limits.h
special.o:	/usr/include/machine/bios.h
special.o:	/usr/include/machine/fpu.h
special.o:	/usr/include/machine/interrupt.h
special.o:	/usr/include/machine/mcontext.h
special.o:	/usr/include/machine/ports.h
special.o:	/usr/include/machine/stackframe.h
special.o:	/usr/include/mathconst.h
special.o:	/usr/include/minix/bitmap.h
special.o:	/usr/include/minix/callnr.h
special.o:	/usr/include/minix/com.h
special.o:	/usr/include/minix/config.h
special.o:	/usr/include/minix/const.h
special.o:	/usr/include/minix/devio.h
special.o:	/usr/include/minix/dir.h
special.o:	/usr/include/minix/dmap.h
special.o:	/usr/include/minix/drivers.h
special.o:	/usr/include/minix/endpoint.h
special.o:	/usr/include/minix/ipc.h
special.o:	/usr/include/minix/ipcconst.h
special.o:	/usr/include/minix/limits.h
special.o:	/usr/include/minix/safecopies.h
special.o:	/usr/include/minix/sef.h
special.o:	/usr/include/minix/spin.h
special.o:	/usr/include/minix/sys_config.h
special.o:	/usr/include/minix/syslib.h
special.o:	/usr/include/minix/sysutil.h
special.o:	/usr/include/minix/timers.h
special.o:	/usr/include/minix/type.h
special.o:	/usr/include/minix/types.h
special.o:	/usr/include/minix/u64.h
special.o:	/usr/include/minix/vm.h
special.o:	/usr/include/stdint.h
special.o:	/usr/include/sys/cdefs.h
special.o:	/usr/include/sys/null.h
special.o:	/usr/include/sys/param.h
special.o:	/usr/include/sys/types.h
special.o:	/usr/include/sys/ucred.h
special.o:	/usr/include/timers.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/ansi.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/limits.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/math.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/signal.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stddef.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stdio.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stdlib.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/string.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/syslimits.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/time.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/unistd.h
special.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include/stdarg.h
special.o:	bitmap.h
special.o:	const.h
special.o:	special.c
special.o:	special.h
special.o:	video_gr.h
