
tower.o:	/usr/include/errno.h
tower.o:	/usr/include/limits.h
tower.o:	/usr/include/machine/bios.h
tower.o:	/usr/include/machine/fpu.h
tower.o:	/usr/include/machine/interrupt.h
tower.o:	/usr/include/machine/mcontext.h
tower.o:	/usr/include/machine/ports.h
tower.o:	/usr/include/machine/stackframe.h
tower.o:	/usr/include/mathconst.h
tower.o:	/usr/include/minix/bitmap.h
tower.o:	/usr/include/minix/callnr.h
tower.o:	/usr/include/minix/com.h
tower.o:	/usr/include/minix/config.h
tower.o:	/usr/include/minix/const.h
tower.o:	/usr/include/minix/devio.h
tower.o:	/usr/include/minix/dir.h
tower.o:	/usr/include/minix/dmap.h
tower.o:	/usr/include/minix/drivers.h
tower.o:	/usr/include/minix/endpoint.h
tower.o:	/usr/include/minix/ipc.h
tower.o:	/usr/include/minix/ipcconst.h
tower.o:	/usr/include/minix/limits.h
tower.o:	/usr/include/minix/safecopies.h
tower.o:	/usr/include/minix/sef.h
tower.o:	/usr/include/minix/spin.h
tower.o:	/usr/include/minix/sys_config.h
tower.o:	/usr/include/minix/syslib.h
tower.o:	/usr/include/minix/sysutil.h
tower.o:	/usr/include/minix/timers.h
tower.o:	/usr/include/minix/type.h
tower.o:	/usr/include/minix/types.h
tower.o:	/usr/include/minix/u64.h
tower.o:	/usr/include/minix/vm.h
tower.o:	/usr/include/stdint.h
tower.o:	/usr/include/sys/cdefs.h
tower.o:	/usr/include/sys/null.h
tower.o:	/usr/include/sys/param.h
tower.o:	/usr/include/sys/types.h
tower.o:	/usr/include/sys/ucred.h
tower.o:	/usr/include/timers.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/ansi.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/limits.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/math.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/signal.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stddef.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stdio.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stdlib.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/string.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/syslimits.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/time.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/unistd.h
tower.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include/stdarg.h
tower.o:	bitmap.h
tower.o:	const.h
tower.o:	tower.c
tower.o:	tower.h
tower.o:	video_gr.h
