
unit.o:	/usr/include/errno.h
unit.o:	/usr/include/limits.h
unit.o:	/usr/include/machine/bios.h
unit.o:	/usr/include/machine/fpu.h
unit.o:	/usr/include/machine/interrupt.h
unit.o:	/usr/include/machine/mcontext.h
unit.o:	/usr/include/machine/ports.h
unit.o:	/usr/include/machine/stackframe.h
unit.o:	/usr/include/mathconst.h
unit.o:	/usr/include/minix/bitmap.h
unit.o:	/usr/include/minix/callnr.h
unit.o:	/usr/include/minix/com.h
unit.o:	/usr/include/minix/config.h
unit.o:	/usr/include/minix/const.h
unit.o:	/usr/include/minix/devio.h
unit.o:	/usr/include/minix/dir.h
unit.o:	/usr/include/minix/dmap.h
unit.o:	/usr/include/minix/drivers.h
unit.o:	/usr/include/minix/endpoint.h
unit.o:	/usr/include/minix/ipc.h
unit.o:	/usr/include/minix/ipcconst.h
unit.o:	/usr/include/minix/limits.h
unit.o:	/usr/include/minix/safecopies.h
unit.o:	/usr/include/minix/sef.h
unit.o:	/usr/include/minix/spin.h
unit.o:	/usr/include/minix/sys_config.h
unit.o:	/usr/include/minix/syslib.h
unit.o:	/usr/include/minix/sysutil.h
unit.o:	/usr/include/minix/timers.h
unit.o:	/usr/include/minix/type.h
unit.o:	/usr/include/minix/types.h
unit.o:	/usr/include/minix/u64.h
unit.o:	/usr/include/minix/vm.h
unit.o:	/usr/include/stdint.h
unit.o:	/usr/include/sys/cdefs.h
unit.o:	/usr/include/sys/null.h
unit.o:	/usr/include/sys/param.h
unit.o:	/usr/include/sys/types.h
unit.o:	/usr/include/sys/ucred.h
unit.o:	/usr/include/timers.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/ansi.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/limits.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/math.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/signal.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stddef.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stdio.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/stdlib.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/string.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/syslimits.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/time.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include-fixed/unistd.h
unit.o:	/usr/pkg/gcc44/lib/gcc/i686-pc-minix/4.4.3/include/stdarg.h
unit.o:	bitmap.h
unit.o:	bullet.h
unit.o:	const.h
unit.o:	test_animation.h
unit.o:	unit.c
unit.o:	unit.h
unit.o:	video_gr.h
